#!/bin/bash -xe

VERSION="v2.3.2"
ARCHIVE="criterion-$VERSION-linux-x86_64.tar.bz2"
DOWNPATH="https://github.com/Snaipe/Criterion/releases/download/$VERSION/$ARCHIVE"

uninstall(){
    find /usr | grep -i criterion | sort -r | xargs rm -vrf
}

install(){
    which curl || apt-get install -y curl
    pushd /tmp
    curl -OL $DOWNPATH
    tar jxf $ARCHIVE
    chown -R root: criterion-$VERSION
    cp    -Rpv     criterion-$VERSION/* /usr
    rm    -rv      criterion-$VERSION*
    popd
}

uninstall
install
